# Numpy

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

In [1]:
import numpy as np

In [17]:
arr = np.array([[1, 2, 3, 4, 5],[4,5,2,4,7]])
print(arr)

[[1 2 3 4 5]
 [4 5 2 4 7]]


In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [12]:
print(arr[0])

[1 2 3 4 5]


In [18]:
print(arr.shape)

(2, 5)


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [20]:
a = np.array([[1,2,3,4],[4,55,1,2],
              [8,3,20,19],[11,2,22,21]])
m = np.reshape(a,(4, 4))
print(m)

[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 8  3 20 19]
 [11  2 22 21]]
